{% set name = "setuptools_dso" %}
{% set version = "1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a9ac5c73b07dd6955ad440b8d44e6ded30fa649e8980f9f0c5369ccfc7e6a3fa

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    - setuptools

test:
  imports:
    - setuptools_dso 

about:
  home: https://github.com/mdavidsaver/setuptools_dso
  license: BSD
  license_file: LICENSE
  summary: 'setuptools extension for building non-Python Dynamic Shared Objects'
  description: |
    setuptools extension for building non-python shared libraries
    and packaging them for distribution.  eg. for use by python extensions.      

extra:
  recipe-maintainers:
    - hhslepicka
