{% set name = "setuptools_dso" %}
{% set version = "2.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 953e66a744e21dbbe4ad73e22b9fee2e47bae739f26bc63ab37473a45b975456

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - setuptools

test:
  requires:
    - python {{ python_min }}
  imports:
    - setuptools_dso

about:
  home: https://github.com/mdavidsaver/setuptools_dso
  license: BSD-3-Clause
  license_file: LICENSE
  summary: setuptools extension for building non-Python Dynamic Shared Objects
  description: |
    setuptools extension for building non-python shared libraries
    and packaging them for distribution.  eg. for use by python extensions.      

extra:
  recipe-maintainers:
    - hhslepicka
    - klauer
