{% set name = "setuptools_dso" %}
{% set version = "2.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a4c3a19db747a70265c9ccc99972f618916d834cb4c2aac4e8f3838419952e6b

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools
  run:
    - python >=3.6
    - setuptools

test:
  imports:
    - setuptools_dso

about:
  home: https://github.com/mdavidsaver/setuptools_dso
  license: BSD-3-Clause
  license_file: LICENSE
  summary: setuptools extension for building non-Python Dynamic Shared Objects
  description: |
    setuptools extension for building non-python shared libraries
    and packaging them for distribution.  eg. for use by python extensions.      

extra:
  recipe-maintainers:
    - hhslepicka
