{% set name = "setuptools_dso" %}
{% set version = "2.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b23019f5e9cec37bc5df3a9735b86ee3948ce7fb2fda42307ca0ba49625d1b44

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools
  run:
    - python >=3.6
    - setuptools

test:
  imports:
    - setuptools_dso

about:
  home: https://github.com/mdavidsaver/setuptools_dso
  license: BSD-3-Clause
  license_file: LICENSE
  summary: setuptools extension for building non-Python Dynamic Shared Objects
  description: |
    setuptools extension for building non-python shared libraries
    and packaging them for distribution.  eg. for use by python extensions.      

extra:
  recipe-maintainers:
    - hhslepicka
    - klauer
