travis:
  secure:
    BINSTAR_TOKEN: Ly3b5tx8p9lcpkgJcJNPkF8sRxotqy/DT5DZqs5TAGjCkUNUHBbZyNBsA9Q9og4DXlO9x6un+a9MLin9dNbzSIrwdRY65teG9+8nAG1zTE3FdplOtnm6Hb8VscE6nw0BqCrKJE4f0zHbUmsJY02rfVZhwftBHmleLAi3MmcLPyWhIUBUrQhVtqR4Kn5c012DEMqdYcCmDmj9yuH6cN0aPlhsAY+2yPWaVhkMaRfj+OzorbFE9D3zxMLrqQARK74oyF2jy7sALG5yCUOSZRem7Pu1vIEHbki53I4S53iEJdedjL8APCgEExsvc6Tf1hmPp5cFTsYX356+QlAN7bWIfUTfsstRLkjnkrJ/G0AQD5xcRnIDL+0IRvv4OZOU0CZrgVgHcYY5AE5PZZAB1mKdV3HLMGgaYcJxQ2hCVHMKe1rBxxRTB+vJmfDk7W4STErFbqtIVeCWYyag0CZRPYrwPTaR1Zbk5RwSix4i5NKuag5l8yD77nuJCDsUfT7wPddRpa1NzbMy/Ws1DwH6rXItdmjomX+mrwAYsvf6xZOVz3RR1l89EdsZkskrkG3eEsclo0B/4pwD6o0P34UPZqHrn1fkumj2Y7WCtj4mXyDdNIqTkrfo4z1B7yDXiLo+SrVK/tlgbJZV0JwMceXmPxK67/5s/caUZMbMKE5Z3H40Ka0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
